include=~/.config/fuzzel/themes/catppuccin-mocha/flamingo.ini

font=MesloLGSDZ Nerd Font:size=8
icon-theme=Papirus-Dark
icons-enabled=no    # le clipboard n'a pas d'icônes utiles

lines=20
width=70            # plus large pour voir les extraits de texte
horizontal-pad=16
vertical-pad=10
inner-pad=4

line-height=15      # un peu plus aéré pour la lecture

[border]
width=2
radius=12

[dmenu]
mode=text
#exit-immediately-if-empty=yes

[key-bindings]
delete-prev-word=none
delete-next=none
custom-4=none
custom-1=Mod1+BackSpace
custom-2=Mod1+space
