include=~/.config/fuzzel/themes/catppuccin-mocha/blue.ini

font=MesloLGSDZ Nerd Font:size=8
icon-theme=Papirus-Dark

lines=12
width=32
horizontal-pad=16
vertical-pad=12
inner-pad=4

[border]
width=2
radius=12

[dmenu]
mode=text
#exit-immediately-if-empty=yes
