source = ~/.config/hypr/hyprland.conf.d/style.conf
source = ~/.config/hypr/hyprland.conf.d/programs.conf
source = ~/.config/hypr/hyprland.conf.d/keybinds.conf


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,auto,1
monitor=DP-4,highres,auto-up,1


#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


###################
### PERMISSIONS ###
###################

# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = fr
    kb_variant = us
    kb_model =
    kb_options = caps:escape_shifted_capslock
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
	clickfinger_behavior = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace
# gestures {
#   workspace_swipe = true
# 	workspace_swipe_touch = true
# }


# Example per-device config
# See https://whyprexpo_gesture = 4, up, hyprexpo:expo, toggleiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

###############
### PLUGINS ###
###############

plugin {
	split-monitor-workspaces {
		count = 5
	}
	hyprexpo-gesture = 3, vertical , expo
    hyprexpo {
        columns = 2
        gap_size = 8
        bg_col = rgb(181825)
        workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

        enable_gesture = true     # laptop touchpad
        gesture_distance = 400    # how far is the "max"
    }
	hyprmodoro {
		notification:use_system_notifications = true
	}
}


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
# windowrule = no_inital_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pinned 0

# For swayosd notification
windowrule = float on, match:class ^swayosd-server$
windowrule = size 280 60, match:class ^swayosd-server$
windowrule = move (monitor_w/2)-100 80, match:class ^swayosd-server$
windowrule = no_initial_focus on, match:class ^swayosd-server$

# Floating terminal
windowrule = float on, match:class ^term-float$
windowrule = size 960 540, match:class ^term-float$
windowrule = center on, match:class ^term-float$

# Blured fs_popup
layerrule = blur on, match:class ^(com\.fspopup\.GtkApplication)$

layerrule = blur on, match:class waybar
# layerrule = ignorezero, waybar
layerrule = ignore_alpha 0.5, match:class waybar

# enable vicinae blur
layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

# disable animation for vicinae only
layerrule {
    name = vicinae-no-animation
    no_anim = on
    match:namespace = vicinae
}

misc {
    focus_on_activate = true
}
