#################
### AUTOSTART ###
#################

# Reset keyboard backlight
exec-once = brightnessctl -rd chromeos::kbd_backlight

exec-once = hyprpm reload -n

exec-once = hyprpaper
# exec-once = swww-daemon --format xrgb
# exec-once = swww img ~/Pictures/wallpapers/evening-sky.png
# exec-once = ~/.local/bin/album-wall.sh

exec-once = $clipboard

exec-once = $osd
exec-once = $notify

exec-once = $low_battery
exec-once = $idle

exec-once = waybar

exec-once = $tmux_script
exec-shutdown = $tmux_save

