#!/usr/bin/env bash
#
# Usage: scripts/build-remote-bundle.sh
#
# Bundles remote/{profile,bashrc,vimrc,tmux.conf,less/lessfilter} into a
# single self-contained installer: remote/install.sh.
# It can be used out of the box (scp'd/curled)
#
# Regenerate remote/install.sh with this script whenever remote/* source
# files change - do not hand-edit install.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/remote"
OUT="$SRC/install.sh"

for dep in base64; do
    command -v "$dep" >/dev/null 2>&1 || { echo "build-remote-bundle: missing dependency: $dep" >&2; exit 1; }
done

encode() {
    base64 -w0 "$1"
}

{
    cat <<'HEADER'
#!/bin/sh
# Generated by scripts/build-remote-bundle.sh - do not edit by hand.
#
# Minimal remote dotfiles installer: bash prompt/history/aliases, a
# stripped less filter, vim defaults, and (opt-in) a bare tmux config.
# No sudo, no package installs, no network calls beyond fetching this
# file itself.
#
# Usage: ./install.sh [--with-tmux|--no-tmux]
#        WITH_TMUX=1 ./install.sh
set -eu

WITH_TMUX="${WITH_TMUX:-}"
for arg in "$@"; do
    case "$arg" in
        --with-tmux) WITH_TMUX=1 ;;
        --no-tmux) WITH_TMUX=0 ;;
    esac
done

if [ -z "$WITH_TMUX" ]; then
    if [ -t 0 ]; then
        printf 'Install tmux config too? [y/N] '
        read -r reply
        case "$reply" in
            y|Y|yes|YES) WITH_TMUX=1 ;;
            *) WITH_TMUX=0 ;;
        esac
    else
        WITH_TMUX=0
    fi
fi

backup() {
    if [ -e "$1" ]; then
        cp -p "$1" "$1.bak.$(date +%Y%m%d%H%M%S)"
    fi
}

install_file() {
    # install_file <target> <base64-payload>
    target="$1"
    mkdir -p "$(dirname "$target")"
    backup "$target"
    printf '%s' "$2" | base64 -d > "$target"
}

HEADER

    printf 'install_file "$HOME/.profile" "%s"\n' "$(encode "$SRC/profile")"
    printf 'install_file "$HOME/.bashrc" "%s"\n' "$(encode "$SRC/bashrc")"
    printf 'install_file "$HOME/.vimrc" "%s"\n' "$(encode "$SRC/vimrc")"
    printf 'mkdir -p "$HOME/.local/state/vim/undo" "$HOME/.local/state/vim/swap" "$HOME/.local/state/vim/backup"\n\n'

    printf 'mkdir -p "$HOME/.config/less"\n'
    printf 'install_file "$HOME/.config/less/lessfilter" "%s"\n' "$(encode "$SRC/less/lessfilter")"
    printf 'chmod +x "$HOME/.config/less/lessfilter"\n\n'

    cat <<'TMUXSTART'
if [ "$WITH_TMUX" = "1" ]; then
TMUXSTART
    printf '    install_file "$HOME/.tmux.conf" "%s"\n' "$(encode "$SRC/tmux.conf")"
    cat <<'TMUXEND'
    echo "tmux config installed (prefix: Ctrl+N, not Ctrl+B)."
fi

TMUXEND

    cat <<'FOOTER'
echo "Minimal remote config installed. Start a new shell (or: exec bash -l) to pick it up."
FOOTER
} > "$OUT"

chmod +x "$OUT"
echo "Wrote $OUT"
