
[env]
TERM = "xterm-256color"

[window]
decorations = "ButtonLess"
dynamic_padding = false
opacity = 0.95
dimensions = { columns = 88, lines = 22}
title = "// um4s                              -->                              Alacritty //"
#dynamic_title = false

[window.padding]
x = 8
y = 5

[scrolling]
history = 100000
multiplier = 5

[font]
size = 18.0
[font.normal]
family="MesloLGSDZ NerdFont"


[keyboard]
bindings = [
 { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
 { key = "W",  mods = "Control|Shift", action = "Quit" },
 { key = "ArrowUp", mods = "Control|Shift", action = "IncreaseFontSize"},
 { key = "ArrowDown", mods= "Control|Shift", action = "DecreaseFontSize"}
]

[general]

live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

