###################
### MY PROGRAMS ###
###################

# App
$terminal = alacritty
$term_float = alacritty --class=term-float

$browser = flatpak run com.brave.Browser
$fileManager = nautilus
$music = flatpak run dev.aunetx.deezer

# Interact
$menu = fuzzel
$bluetooth_menu = bzmenu -l custom --launcher-command "fuzzel --dmenu --config $HOME/.config/fuzzel/bluetooth.ini"
$wifi_menu = iwmenu -l custom --launcher-command "fuzzel --dmenu --config $HOME/.config/fuzzel/wifi.ini"
env = CLIPHIST_TERMINAL,alacritty
$clipboard_menu=~/.config/hypr/scripts/cliphist-fzf.sh
$calc = alacritty --class=term-float -e qalc

# Daemon
$clipboard = wl-paste --watch cliphist store --max-items 200
$osd = systemctl --user enable --now swayosd.service
$notify = swaync
$low_battery = systemctl --user enable --now low_battery.timer
$idle = ~/.config/hypr/scripts/start_hypridle_service.sh


$tmux_script = ~/.config/hypr/scripts/tmux-boot.sh
$tmux_save = ~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh

source = ~/.config/hypr/hyprland.conf.d/autostart.conf
